apiVersion: v1 
kind: ReplicationController 
metadata:
  name: ashurcnew1  # name of RC 
spec:
  replicas: 1 # number of pods 
  selector: 
      name: ok
  template: 
    metadata:
      name: ashupod1 
      labels:  # Labels to apply to the pod template
        name: ok  # Label to match the selector
    spec:
      containers:
      - name: ashuc1 
        image: nginx
