apiVersion: v1
data:
  ashu-pass: Um9jaGVEYkAwOTgk
kind: Secret
metadata:
  creationTimestamp: null
  name: ashudb-root-cred

--- 
apiVersion: v1
data:
  MYSQL_PASSWORD: QXNodWRiQDA5OA==
  MYSQL_USER: YXNodQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ashudb-generaldb-cred