apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ashu-rolenew1
  namespace: ashu-developer
rules:
- apiGroups:
  - """
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
