apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::751136288263:role/roche-eks-dataplane
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::751136288263:role/roche-eks-dataplane\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::751136288263:user/ashu-dev\n  username: ashu-dev\n  groups:\n  - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-04-15T09:50:10Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"645868","uid":"da4e9ddd-ca6a-4197-9428-beb9ca707736"}}
  creationTimestamp: "2024-04-15T09:50:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "666012"
  uid: da4e9ddd-ca6a-4197-9428-beb9ca707736
