apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ashu-bind1
  namespace: ashu-developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ashu-pod-read-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ashu-roche-user1